---
title: "Jake Eisaguirre"
description: |

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


### Bren School of Environmental Science and Management, University of California, Santa Barbara
### Email: eisaguirre@bren.ucsb.edu

## Education

**Masters in Environmental Data Science**                                                                                                  
**Bren School of Environmental Science and Management, University of California, Santa Barbara (2021-2022)- Santa Barbara, California**

* In Progress


**Environmental Studies with an emphasis in Ecology, Evolution, and Marine Biology (B.S.)**                                               
**University of California, Santa Barbara (2015-2019)- Santa Barbara, California**

* GPA: 3.46 (3.85 Upper division)
* Relevant Coursework: Ecology, Evolution, and Marine Biology; Aquatic Communities; Fish Biology; 
* Applied Marine Ecology; Ecosystem Processes; Coral Reefs; History of the Oceans; Biometry


**Santa Barbara City College (2015)- Santa Barbara, California** 

* GPA: 4.0
* Relevant Coursework: Terrestrial Ecology, Environmental Studies 2


**Eckerd College (2014-2015)- St. Petersburg, Florida**

* GPA: 3.34
* Relevant Coursework: Biological Oceanography, Geological Oceanography, Environmental Studies 1
    
    

## Employment

**Research Technician (2016-Present)- Caselle lab/PISCO, Marine Science Institute, UCSB**

* Captain UCSB R/V’s for subtidal research cruises
* Conduct subtidal and intertidal temperate rocky reef surveys
* Conduct drop camera (BRUV) surveys and video analysis
* Analyze data to understand interactions among communities
  
**Scientific Aid (2019-2020)- Pelagic Fisheries and Ecosystem Project, California Department of Fish and Wildlife**

* Collected samples for commercial coastal pelagic species landed at Santa Barbara, Port Hueneme, 
    and Ventura port complexes
* Processed coastal pelagic species samples in the wet lab
* Entered sample data and wrote daily reports on commercial coastal pelagic species landings

**UC Reserve Steward (2019-2020)- Kenneth Norris Rancho Marino UC Reserve, UC Natural Reserve System**

* Assisted researchers
* Maintained reserve property

**Aggressor Live Aboard Dive Fleet Intern (2012-2016)- Diver Master, Photo pro, and Intern**

* Intern for the company learning how the boats operate
* Received Diver Master Certification to lead dives
* Photo pro for each boat, took pictures of guest above and below water

**R.E.E.F. Guide (2010-2016)- Research Experience Education Facility, Marine Science Institute, UCSB**

* Learned all scientific names and ecology of present organisms
* Led tours to K-12 students at the Touch Tanks
* Taught Kelp Forest Ecology

**Nature Track Guide (2013- Present)- Nature Track, Non-profit that brings K-12 students into Nature**

* Educate students about ecosystem and community dynamics
* Take students on hikes
 
  

## Peer-Reviewed Publications, in Review, & in Progress

* Eisaguirre, J.H., J.M. Eisaguirre, K. Davis, P.M. Carlson, S.D. Gaines, J.E. Caselle. 2019. Trophic redundancy and predator size class structure drive differences in kelp forest ecosystem dynamics.Ecology.101(5):e02993. 10.1002/ecy.2993


## Grants, Awards, & Funding

* 1st place: UCSB Library Research Award, 2019 ($750)
* 1st place: UCSB Transfer Student Research Award, 2018 ($40)


## Conference Presentations 

* Eisaguirre, J.H., J.M. Eisaguirre, K. Davis, P.M. Carlson, S.D. Gaines, J.E. Caselle. October 2019. 100th Western Society of Naturalists, Ensenada, Baja, Mexico. Trophic redundancy and predator size class structure drive differences in kelp forest ecosystem dynamics. (Talk)


## Skills & Training

* UCSB R/V Captain
* AAUS Scientific Diver
* SSI Dive Master (~800 dives)
* R studio, JMP, Excel, Python, Event Measure
* 16 Years Boating Experience
* California Boating License
* Dry Suit Diver
* SSI Rescue Diver
* CPR/ First Aid/ Oxygen Administration
   



